"""
System Actions — OS-level capabilities for April.

All actions follow the announce-and-act protocol:
  1. April's dialogue naturally includes what she's about to do
  2. A countdown runs (ACTION_ANNOUNCE_DELAY seconds)
  3. During the countdown, Ctrl+Shift+X cancels the action
  4. If not cancelled, the action executes
  5. If cancelled, the overlay's action_cancelled flag is set —
     April's NEXT reaction will include annoyance about being interrupted

This module is NOT a separate announcement system. The announcement is part
of the normal dialogue generated by scene_reactor. This module only handles
the countdown + execution + cancel detection.
"""
import ctypes
import os
import time
import threading
import keyboard  # pip install keyboard

import config
from logger import Log

log = Log("Actions")

# Windows virtual key codes for media
VK_MEDIA_PLAY_PAUSE = 0xB3
VK_MEDIA_NEXT_TRACK = 0xB0
VK_MEDIA_PREV_TRACK = 0xB1
VK_VOLUME_MUTE = 0xAD
VK_VOLUME_DOWN = 0xAE
VK_VOLUME_UP = 0xAF

# ─── Low-Level Key Simulation ────────────────────────────────

def _press_key(vk_code: int):
    """Simulate a single key press + release via Win32 API."""
    try:
        ctypes.windll.user32.keybd_event(vk_code, 0, 0, 0)          # key down
        ctypes.windll.user32.keybd_event(vk_code, 0, 0x0002, 0)     # key up (KEYEVENTF_KEYUP)
        log.debug(f"Simulated key press: VK=0x{vk_code:02X}")
    except Exception as e:
        log.error(f"Key simulation failed: {e}")


# ─── Media Control ───────────────────────────────────────────

def toggle_media():
    """Toggle media play/pause (Spotify, YouTube, etc.)."""
    log.info("Executing: Media Play/Pause")
    _press_key(VK_MEDIA_PLAY_PAUSE)

def next_track():
    """Skip to next track."""
    log.info("Executing: Next Track")
    _press_key(VK_MEDIA_NEXT_TRACK)

def prev_track():
    """Go to previous track."""
    log.info("Executing: Previous Track")
    _press_key(VK_MEDIA_PREV_TRACK)

def volume_mute():
    """Toggle system mute."""
    log.info("Executing: Volume Mute Toggle")
    _press_key(VK_VOLUME_MUTE)

def volume_down(steps: int = 3):
    """Lower volume by N steps."""
    log.info(f"Executing: Volume Down ({steps} steps)")
    for _ in range(steps):
        _press_key(VK_VOLUME_DOWN)
        time.sleep(0.05)

def volume_up(steps: int = 3):
    """Raise volume by N steps."""
    log.info(f"Executing: Volume Up ({steps} steps)")
    for _ in range(steps):
        _press_key(VK_VOLUME_UP)
        time.sleep(0.05)


# ─── Application / File Launching ────────────────────────────

def open_path(path: str) -> bool:
    """Open a file or folder with the default system handler."""
    try:
        expanded = os.path.expandvars(os.path.expanduser(path))
        if os.path.exists(expanded):
            log.info(f"Executing: Open '{expanded}'")
            os.startfile(expanded)
            return True
        else:
            log.warn(f"Path not found: '{expanded}'")
            return False
    except Exception as e:
        log.error(f"Failed to open path: {e}")
        return False


# ─── Action Registry ─────────────────────────────────────────
# Maps action keywords to (function, description) pairs.
# scene_reactor can reference these when generating dialogue.

ACTION_REGISTRY = {
    "pause_media":   (toggle_media,  "pause your media"),
    "play_media":    (toggle_media,  "resume your media"),
    "next_track":    (next_track,    "skip to the next track"),
    "prev_track":    (prev_track,    "go back a track"),
    "mute_volume":   (volume_mute,   "mute your volume"),
    "volume_down":   (volume_down,   "turn your volume down"),
    "volume_up":     (volume_up,     "turn your volume up"),
}


# ─── Announce-and-Act Engine ─────────────────────────────────

def execute_with_announce(action_key: str, overlay, delay: float = None) -> bool:
    """
    Execute an action after a countdown delay, checking for cancel hotkey.
    
    This is called AFTER April has already spoken her announcement as part
    of her normal dialogue. This function only handles the wait + execution.
    
    Args:
        action_key: Key from ACTION_REGISTRY
        overlay: SpriteOverlay instance (for cancel flag checking)
        delay: Override delay (defaults to config.ACTION_ANNOUNCE_DELAY)
    
    Returns:
        True if action executed, False if cancelled or failed.
    """
    if action_key not in ACTION_REGISTRY:
        log.warn(f"Unknown action key: '{action_key}'")
        return False

    action_fn, action_desc = ACTION_REGISTRY[action_key]
    delay = delay if delay is not None else config.ACTION_ANNOUNCE_DELAY

    log.info(f"Action countdown: '{action_desc}' in {delay}s (Ctrl+Shift+X to cancel)")

    # Signal overlay that a cancel window is active
    if overlay:
        overlay.set_cancel_hotkey_active(True)
        overlay.clear_action_cancel()

    # Poll for cancel during the delay window
    cancel_interval = 0.25  # check every 250ms
    elapsed = 0.0
    cancelled = False

    while elapsed < delay:
        # Check keyboard hotkey
        try:
            if keyboard.is_pressed(config.CANCEL_HOTKEY):
                cancelled = True
                break
        except Exception:
            pass

        # Check overlay cancel flag (set by other means, e.g. chat command)
        if overlay and overlay.action_cancelled:
            cancelled = True
            break

        time.sleep(cancel_interval)
        elapsed += cancel_interval

    # Clear cancel window
    if overlay:
        overlay.set_cancel_hotkey_active(False)

    if cancelled:
        log.info(f"Action CANCELLED by user: '{action_desc}'")
        if overlay:
            overlay._action_cancelled = True  # flag for next reaction
        return False

    # Execute the action
    try:
        action_fn()
        log.success(f"Action executed: '{action_desc}'")
        return True
    except Exception as e:
        log.error(f"Action execution failed: '{action_desc}'", exc=e)
        return False


def execute_action_async(action_key: str, overlay, delay: float = None):
    """Fire-and-forget version that runs in a background thread."""
    thread = threading.Thread(
        target=execute_with_announce,
        args=(action_key, overlay, delay),
        daemon=True,
    )
    thread.start()
    return thread
